name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: 0 8 * * *
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-vscode-extensions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        name: Install Nix
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update All Systems
        run: nix develop -c fish ./update_all.fish

      - uses: EndBug/add-and-commit@v8
        with:
          add: 'systems'
          default_author: github_actor
          message: 'Updated Visual Studio Code Insiders build'
